config/routes.rb
Rails.application.routes.draw do
  resources :car_files

  root 'car_files#index'

end

app/models/car.rb
class Car < ActiveRecord::Base
  belongs_to :owner
end

app/models/car_file.rb
class CarFile < ActiveRecord::Base
  belongs_to :office
  belongs_to :car
  has_many :records
end

app/models/office.rb
class Office < ActiveRecord::Base
  belongs_to :workshop
  has_many :car_files
end

app/models/owner.rb
class Owner < ActiveRecord::Base
	has_many :cars
end

app/models/record.rb
class Record < ActiveRecord::Base
  belongs_to :car_file
end

app/models/workshop.rb
class Workshop < ActiveRecord::Base
	has_many :offices
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/car_files_controller.rb
class CarFilesController < ApplicationController
  before_action :set_car_file, only: [:show, :edit, :update, :destroy]

  # GET /car_files
  # GET /car_files.json
  def index
    @car_files = CarFile.all
  end

  # GET /car_files/1
  # GET /car_files/1.json
  def show
  end

  # GET /car_files/new
  def new
    @car_file = CarFile.new
  end

  # GET /car_files/1/edit
  def edit
  end

  # POST /car_files
  # POST /car_files.json
  def create
    @car_file = CarFile.new(car_file_params)

    respond_to do |format|
      if @car_file.save
        format.html { redirect_to @car_file, notice: 'Car file was successfully created.' }
        format.json { render :show, status: :created, location: @car_file }
      else
        format.html { render :new }
        format.json { render json: @car_file.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /car_files/1
  # PATCH/PUT /car_files/1.json
  def update
    respond_to do |format|
      if @car_file.update(car_file_params)
        format.html { redirect_to @car_file, notice: 'Car file was successfully updated.' }
        format.json { render :show, status: :ok, location: @car_file }
      else
        format.html { render :edit }
        format.json { render json: @car_file.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /car_files/1
  # DELETE /car_files/1.json
  def destroy
    @car_file.destroy
    respond_to do |format|
      format.html { redirect_to car_files_url, notice: 'Car file was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_car_file
      @car_file = CarFile.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def car_file_params
      params.require(:car_file).permit(:office_id, :car_id)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/car_files_helper.rb
module CarFilesHelper
end

app/views/car_files/_form.html.erb
<%= form_for(@car_file) do |f| %>
  <% if @car_file.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@car_file.errors.count, "error") %> prohibited this car_file from being saved:</h2>

      <ul>
      <% @car_file.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :office_id %><br>
    <%= f.text_field :office_id %>
  </div>
  <div class="field">
    <%= f.label :car_id %><br>
    <%= f.text_field :car_id %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/car_files/edit.html.erb
<h1>Editing Car File</h1>

<%= render 'form' %>

<%= link_to 'Show', @car_file %> |
<%= link_to 'Back', car_files_path %>

app/views/car_files/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Car Files</h1>

<table>
  <thead>
    <tr>
      <th>Office</th>
      <th>Car</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @car_files.each do |car_file| %>
      <tr>
        <td><%= car_file.office %></td>
        <td><%= car_file.car %></td>
        <td><%= link_to 'Show', car_file %></td>
        <td><%= link_to 'Edit', edit_car_file_path(car_file) %></td>
        <td><%= link_to 'Destroy', car_file, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Car file', new_car_file_path %>

app/views/car_files/new.html.erb
<h1>New Car File</h1>

<%= render 'form' %>

<%= link_to 'Back', car_files_path %>

app/views/car_files/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Office:</strong>
  <%= @car_file.office %>
</p>

<p>
  <strong>Car:</strong>
  <%= @car_file.car %>
</p>

<%= link_to 'Edit', edit_car_file_path(@car_file) %> |
<%= link_to 'Back', car_files_path %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Chevy</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>